/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemesIdRouteImport } from './routes/schemes.$id'

const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIdRoute = SchemesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchemesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/copilot': typeof CopilotRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/copilot': typeof CopilotRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/copilot': typeof CopilotRoute
  '/profile': typeof ProfileRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/complaints' | '/copilot' | '/profile' | '/schemes' | '/schemes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/complaints' | '/copilot' | '/profile' | '/schemes' | '/schemes/$id'
  id:
    | '__root__'
    | '/'
    | '/complaints'
    | '/copilot'
    | '/profile'
    | '/schemes'
    | '/schemes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplaintsRoute: typeof ComplaintsRoute
  CopilotRoute: typeof CopilotRoute
  ProfileRoute: typeof ProfileRoute
  SchemesRoute: typeof SchemesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$id': {
      id: '/schemes/$id'
      path: '/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof SchemesIdRouteImport
      parentRoute: typeof SchemesRoute
    }
  }
}

interface SchemesRouteChildren {
  SchemesIdRoute: typeof SchemesIdRoute
}

const SchemesRouteChildren: SchemesRouteChildren = {
  SchemesIdRoute: SchemesIdRoute,
}

const SchemesRouteWithChildren =
  SchemesRoute._addFileChildren(SchemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplaintsRoute: ComplaintsRoute,
  CopilotRoute: CopilotRoute,
  ProfileRoute: ProfileRoute,
  SchemesRoute: SchemesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
